/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurgeRouteImport } from './routes/purge'
import { Route as LokasiSlugIndexRouteImport } from './routes/lokasi.$slug.index'
import { Route as LokasiSlugTipeTipeRouteImport } from './routes/lokasi.$slug.tipe.$tipe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurgeRoute = PurgeRouteImport.update({
  id: '/purge',
  path: '/purge',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiSlugIndexRoute = LokasiSlugIndexRouteImport.update({
  id: '/lokasi/$slug/',
  path: '/lokasi/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LokasiSlugTipeTipeRoute = LokasiSlugTipeTipeRouteImport.update({
  id: '/lokasi/$slug/tipe/$tipe',
  path: '/lokasi/$slug/tipe/$tipe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/purge': typeof PurgeRoute
  '/lokasi/$slug/': typeof LokasiSlugIndexRoute
  '/lokasi/$slug/tipe/$tipe': typeof LokasiSlugTipeTipeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/purge': typeof PurgeRoute
  '/lokasi/$slug': typeof LokasiSlugIndexRoute
  '/lokasi/$slug/tipe/$tipe': typeof LokasiSlugTipeTipeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/purge': typeof PurgeRoute
  '/lokasi/$slug/': typeof LokasiSlugIndexRoute
  '/lokasi/$slug/tipe/$tipe': typeof LokasiSlugTipeTipeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/purge' | '/lokasi/$slug/' | '/lokasi/$slug/tipe/$tipe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/purge' | '/lokasi/$slug' | '/lokasi/$slug/tipe/$tipe'
  id:
    '__root__' | '/' | '/purge' | '/lokasi/$slug/' | '/lokasi/$slug/tipe/$tipe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PurgeRoute: typeof PurgeRoute
  LokasiSlugIndexRoute: typeof LokasiSlugIndexRoute
  LokasiSlugTipeTipeRoute: typeof LokasiSlugTipeTipeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purge': {
      id: '/purge'
      path: '/purge'
      fullPath: '/purge'
      preLoaderRoute: typeof PurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi/$slug/': {
      id: '/lokasi/$slug/'
      path: '/lokasi/$slug'
      fullPath: '/lokasi/$slug/'
      preLoaderRoute: typeof LokasiSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lokasi/$slug/tipe/$tipe': {
      id: '/lokasi/$slug/tipe/$tipe'
      path: '/lokasi/$slug/tipe/$tipe'
      fullPath: '/lokasi/$slug/tipe/$tipe'
      preLoaderRoute: typeof LokasiSlugTipeTipeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PurgeRoute: PurgeRoute,
  LokasiSlugIndexRoute: LokasiSlugIndexRoute,
  LokasiSlugTipeTipeRoute: LokasiSlugTipeTipeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
